-- Criação do banco de dados e tabelas
CREATE DATABASE db_curso;
GO
USE db_curso;
GO

CREATE TABLE TB_ESTADO (
    SIGLA_ESTADO CHAR(2) NOT NULL,
    NOME_ESTADO VARCHAR(40)
);

CREATE TABLE TB_CLASSE (
    ID_CLASSE SMALLINT NOT NULL,
    ID_ANDAR SMALLINT
);

CREATE TABLE TB_PROFESSOR (
    ID_PROFESSOR CHAR(3) NOT NULL,
    NOME_PROFESSOR VARCHAR(30)
);

CREATE TABLE TB_ALUNO (
    COD_ALUNO SMALLINT NOT NULL,
    NOME_ALUNO VARCHAR(40),
    END_ALUNO VARCHAR(30),
    SIGLA_ESTADO CHAR(2),
    ID_CLASSE SMALLINT
);

CREATE TABLE TB_DISCIPLINA (
    ID_DISCIPLINA CHAR(3) NOT NULL,
    NOME_DISCIPLINA VARCHAR(15),
    ID_PROFESSOR CHAR(3),
    NOTA_MINIMA_DISCIPLINA SMALLINT
);

CREATE TABLE TB_ALUNO_DISCIPLINA (
    COD_ALUNO SMALLINT NOT NULL,
    ID_DISCIPLINA CHAR(3) NOT NULL,
    NOTA_ALUNO SMALLINT
);
GO

-- Chaves primárias
ALTER TABLE TB_ESTADO ADD CONSTRAINT PK_TB_ESTADO PRIMARY KEY (SIGLA_ESTADO);
ALTER TABLE TB_CLASSE ADD CONSTRAINT PK_TB_CLASSE PRIMARY KEY (ID_CLASSE);
ALTER TABLE TB_PROFESSOR ADD CONSTRAINT PK_TB_PROFESSOR PRIMARY KEY (ID_PROFESSOR);
ALTER TABLE TB_ALUNO ADD CONSTRAINT PK_TB_ALUNO PRIMARY KEY (COD_ALUNO);
ALTER TABLE TB_DISCIPLINA ADD CONSTRAINT PK_TB_DISCIPLINA PRIMARY KEY (ID_DISCIPLINA);
ALTER TABLE TB_ALUNO_DISCIPLINA ADD CONSTRAINT PK_TB_ALUNO_DISCIPLINA PRIMARY KEY (COD_ALUNO, ID_DISCIPLINA);
GO

-- Chaves estrangeiras
ALTER TABLE TB_ALUNO ADD CONSTRAINT FK_TB_ALUNO_TB_ESTADO FOREIGN KEY (SIGLA_ESTADO) REFERENCES TB_ESTADO(SIGLA_ESTADO);
ALTER TABLE TB_ALUNO ADD CONSTRAINT FK_TB_ALUNO_TB_CLASSE FOREIGN KEY (ID_CLASSE) REFERENCES TB_CLASSE(ID_CLASSE);
ALTER TABLE TB_DISCIPLINA ADD CONSTRAINT FK_TB_DISCIPLINA_TB_PROFESSOR FOREIGN KEY (ID_PROFESSOR) REFERENCES TB_PROFESSOR(ID_PROFESSOR);
ALTER TABLE TB_ALUNO_DISCIPLINA ADD CONSTRAINT FK_TB_ALUNO_DISCIPLINA_TB_ALUNO FOREIGN KEY (COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO);
ALTER TABLE TB_ALUNO_DISCIPLINA ADD CONSTRAINT FK_TB_ALUNO_DISCIPLINA_TB_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES TB_DISCIPLINA(ID_DISCIPLINA);
GO

-- Inserção dos dados
INSERT INTO TB_ESTADO VALUES ('SP', 'SAO PAULO');

INSERT INTO TB_CLASSE VALUES (1, 1);
INSERT INTO TB_CLASSE VALUES (2, 2);
INSERT INTO TB_CLASSE VALUES (3, 3);

INSERT INTO TB_PROFESSOR VALUES ('JOI', 'JOILSON CARDOSO');
INSERT INTO TB_PROFESSOR VALUES ('OSE', 'OSEAS SANTANA');
INSERT INTO TB_PROFESSOR VALUES ('VIT', 'VITOR VASCONCELOS');
INSERT INTO TB_PROFESSOR VALUES ('FER', 'JOSE ROBERTO FERROLI');
INSERT INTO TB_PROFESSOR VALUES ('LIM', 'VALMIR LIMA');
INSERT INTO TB_PROFESSOR VALUES ('EDS', 'EDSON SILVA');
INSERT INTO TB_PROFESSOR VALUES ('WAG', 'WAGNER OKIDA');

INSERT INTO TB_ALUNO VALUES (1, 'ANTONIO CARLOS PENTEADO', 'RUA X', 'SP', 1);
INSERT INTO TB_ALUNO VALUES (2, 'AUROMIR DA SILVA VALDEVINO', 'RUA W', 'SP', 1);
INSERT INTO TB_ALUNO VALUES (3, 'ANDRE COSTA', 'RUA T', 'SP', 2);
INSERT INTO TB_ALUNO VALUES (4, 'ROBERTO SOARES DE MENEZES', 'RUA BW', 'SP', 2);
INSERT INTO TB_ALUNO VALUES (5, 'DANIA', 'RUA CCC', 'SP', 2);
INSERT INTO TB_ALUNO VALUES (6, 'CARLOS MAGALHAES', 'AV SP', 'SP', 2);
INSERT INTO TB_ALUNO VALUES (7, 'MARCELO BAUBA', 'AV SAO LUIS', 'SP', 3);
INSERT INTO TB_ALUNO VALUES (8, 'FERNANDO', 'AV COUNTYR', 'SP', 3);
INSERT INTO TB_ALUNO VALUES (9, 'WALMIR BURIN', 'RUA SSISIS', 'SP', 3);

INSERT INTO TB_DISCIPLINA VALUES ('MAT', 'MATEMATICA', 'JOI', 7);
INSERT INTO TB_DISCIPLINA VALUES ('POR', 'PORTUGUES', 'VIT', 5);
INSERT INTO TB_DISCIPLINA VALUES ('FIS', 'FISICA', 'OSE', 3);
INSERT INTO TB_DISCIPLINA VALUES ('HIS', 'HISTORIA', 'EDS', 2);
INSERT INTO TB_DISCIPLINA VALUES ('GEO', 'GEOGRAFIA', 'WAG', 4);
INSERT INTO TB_DISCIPLINA VALUES ('ING', 'INGLES', 'LIM', 2);

INSERT INTO TB_ALUNO_DISCIPLINA VALUES (1, 'MAT', 0);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (2, 'MAT', 0);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (3, 'MAT', 1);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (4, 'POR', 2);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (5, 'POR', 2);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (6, 'POR', 2);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (7, 'FIS', 3);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (8, 'FIS', 3);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (9, 'FIS', 3);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (1, 'POR', 2);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (2, 'POR', 2);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (7, 'POR', 2);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (1, 'FIS', 3);
GO

-- ========================================
-- EXERCICIOS DE SELECT
-- ========================================

-- A1) Selecionar todos os alunos cadastrados
SELECT * FROM TB_ALUNO;

-- A2) Nomes de disciplina com nota minima maior que 5
SELECT NOME_DISCIPLINA
FROM TB_DISCIPLINA
WHERE NOTA_MINIMA_DISCIPLINA > 5;

-- A3) Disciplinas com nota minima entre 3 e 5
SELECT *
FROM TB_DISCIPLINA
WHERE NOTA_MINIMA_DISCIPLINA BETWEEN 3 AND 5;

-- B1) Alunos em ordem alfabetica, com numero da classe
SELECT NOME_ALUNO, ID_CLASSE
FROM TB_ALUNO
ORDER BY NOME_ALUNO;

-- B2) Mesmo item anterior, ordenado por codigo do aluno de forma descendente
SELECT NOME_ALUNO, ID_CLASSE
FROM TB_ALUNO
ORDER BY COD_ALUNO DESC;

-- B3) Alunos que cursam Matematica E Portugues, agrupados por aluno e disciplina
SELECT COD_ALUNO, ID_DISCIPLINA
FROM TB_ALUNO_DISCIPLINA
WHERE COD_ALUNO IN (
    SELECT COD_ALUNO
    FROM TB_ALUNO_DISCIPLINA
    WHERE ID_DISCIPLINA IN ('MAT', 'POR')
    GROUP BY COD_ALUNO
    HAVING COUNT(DISTINCT ID_DISCIPLINA) = 2
)
GROUP BY COD_ALUNO, ID_DISCIPLINA;

-- C1) Nomes de alunos que cursam Portugues ou Matematica
SELECT DISTINCT A.NOME_ALUNO
FROM TB_ALUNO A
JOIN TB_ALUNO_DISCIPLINA AD ON A.COD_ALUNO = AD.COD_ALUNO
WHERE AD.ID_DISCIPLINA IN ('MAT', 'POR');

-- C2) Nomes e enderecos de alunos que cursam Fisica
SELECT DISTINCT A.NOME_ALUNO, A.END_ALUNO
FROM TB_ALUNO A
JOIN TB_ALUNO_DISCIPLINA AD ON A.COD_ALUNO = AD.COD_ALUNO
WHERE AD.ID_DISCIPLINA = 'FIS';

-- C3) Nomes de alunos que cursam Fisica e o andar da classe
SELECT DISTINCT A.NOME_ALUNO,
       'andar ' + CAST(C.ID_ANDAR AS VARCHAR(10)) AS ANDAR
FROM TB_ALUNO A
JOIN TB_ALUNO_DISCIPLINA AD ON A.COD_ALUNO = AD.COD_ALUNO
JOIN TB_CLASSE C ON A.ID_CLASSE = C.ID_CLASSE
WHERE AD.ID_DISCIPLINA = 'FIS';

-- D1) Professores com suas disciplinas, incluindo os que nao lecionam nenhuma
SELECT P.NOME_PROFESSOR, D.NOME_DISCIPLINA
FROM TB_PROFESSOR P
LEFT JOIN TB_DISCIPLINA D ON P.ID_PROFESSOR = D.ID_PROFESSOR;

-- E1) Professores que lecionaram para alunos do Piaui, classe no 3 andar
SELECT NOME_PROFESSOR
FROM TB_PROFESSOR
WHERE ID_PROFESSOR IN (
    SELECT ID_PROFESSOR
    FROM TB_DISCIPLINA
    WHERE ID_DISCIPLINA IN (
        SELECT ID_DISCIPLINA
        FROM TB_ALUNO_DISCIPLINA
        WHERE COD_ALUNO IN (
            SELECT COD_ALUNO
            FROM TB_ALUNO
            WHERE SIGLA_ESTADO = 'PI'
            AND ID_CLASSE IN (
                SELECT ID_CLASSE FROM TB_CLASSE WHERE ID_ANDAR = 3
            )
        )
    )
);
GO